const fs=require('fs');const path=require('path');const esbuild=require('esbuild');const sass=require('sass');
(async()=>{
 const root=path.resolve(__dirname,'..');process.chdir(root);fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist',{recursive:true});fs.cpSync('public','dist',{recursive:true});
 await esbuild.build({absWorkingDir:root,entryPoints:['src/main.ts'],bundle:true,outfile:'dist/game.js',minify:true,target:['es2020'],jsxFactory:'React.createElement',jsxFragment:'React.Fragment',loader:{'.png':'file','.jpg':'file','.webp':'file','.ogg':'file'},assetNames:'assets/[name]-[hash]',define:{'process.env.NODE_ENV':'"production"','global':'globalThis'},alias:{'~':path.join(root,'src'),'phaser':path.join(root,'node_modules/phaser/dist/phaser.js')},logLevel:'info'});
 let styles=sass.renderSync({file:'src/styles/styles.scss'}).css.toString().replaceAll('../../public/assets/','assets/');styles=fs.readFileSync('node_modules/bulmaswatch/superhero/bulmaswatch.min.css','utf8')+'\n'+styles;
 // Game UI theme precedes custom menu rules. Font CSS is emitted by esbuild.
 fs.writeFileSync('dist/legacy.css',styles);
 const bundleId=require('crypto').createHash('sha256').update(fs.readFileSync('dist/game.js')).update(fs.readFileSync('dist/game.css')).update(fs.readFileSync('dist/legacy.css')).digest('hex').slice(0,12);
 fs.writeFileSync('dist/index.html',`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Joystick Pop</title><link rel="icon" href="assets/game/favicon-48.png"><link rel="stylesheet" href="legacy.css?v=${bundleId}"><link rel="stylesheet" href="game.css?v=${bundleId}"></head><body><div id="pop-boot" style="position:fixed;inset:0;z-index:90;display:grid;place-items:center;background:#10263f;color:#ffe298;font:20px Arial;text-align:center;padding:25px"><span id="pop-boot-label">Cargando Joystick Pop…</span></div><script>window.addEventListener("error",function(){var b=document.getElementById("pop-boot-label");if(b)b.textContent="No se pudo iniciar el juego. Recargá la página.";});</script><div class="game-wrapper"><div id="phaser-container"></div></div><script src="game.js?v=${bundleId}"></script></body></html>`);
})().catch(e=>{console.error(e);process.exit(1)});
